# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nrontey <nrontey@student.42angouleme.fr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/30 11:26:03 by nrontey           #+#    #+#              #
#    Updated: 2025/02/12 00:25:13 by nrontey          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Forms

src = Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp Intern.cpp

include ../ex00/Makefile
