# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nrontey <nrontey@student.42angouleme.fr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/02 23:33:55 by nrontey           #+#    #+#              #
#    Updated: 2025/01/15 23:13:45 by nrontey          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = animal

src = Animal.cpp Dog.cpp Cat.cpp Brain.cpp

include ../ex00/Makefile