# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nrontey <nrontey@student.42angouleme.fr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/02 23:33:55 by nrontey           #+#    #+#              #
#    Updated: 2025/01/16 00:41:43 by nrontey          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = animal

src = AAnimal.cpp Dog.cpp Cat.cpp Brain.cpp WrongAnimal.cpp WrongCat.cpp

include ../ex00/Makefile
